apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ include "hord-watcher-chart.serviceAccountName" . }}-clusterrole-binding
subjects:
- kind: ServiceAccount
  name: {{ include "hord-watcher-chart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "hord-watcher-chart.serviceAccountName" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io