apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hord-watcher-chart.serviceAccountName" . }}-clusterrole
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["events"]
  verbs: ["get", "watch", "list"]
