name: Docker Image CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
permissions:
  packages: write
  contents: read
env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: Swatinem/rust-cache@v2.3.0
      with:
        prefix-key: "v0"
    - name: Build Release
      run: cargo build --release
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
      with:
        images: ghcr.io/${{github.repository}}
    - name: 'Publishing Image'
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

