name: "Master Build"
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31.6.2
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix flake check
