name: "Release Build"
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
permissions:
  packages: write
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix flake check
    - run: nix build .#dockerImage
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: 'Publishing Image'
      run: |
        docker load < result
        docker push ghcr.io/${{github.repository}}:latest
        docker tag ghcr.io/${{github.repository}}:latest ghcr.io/${{github.repository}}:${RELEASE_VERSION}
        docker push ghcr.io/${{github.repository}}:${RELEASE_VERSION}
